### ISSUE TITLE
Some error in the ReadMe

### ISSUE THREAD

**Issue by sonomirco** [Slashgear/action-check-pr-title#36]
**Describe the bug**
Some error into the ReadMe.

**To Reproduce**
```
steps:
- uses: Slashgear/action-check-pr-title@2.0.0
  with:
    regex: '([a-z])+' # Regex the title should match.
```

Slashgear/action-check-pr-title@v2.0.0
regexp: '([a-z])+' # Regex the title should match.

Also, I am using Regex by default
`regexp: '([a-z])+' `
and it doesn't pass an error if I pass a title like this `Dev/mibi/label action and Download`
